### ISSUE TITLE
Support for Webdriverio 7?

### ISSUE THREAD

**Issue by YannVerr** [fijijavis/wdio-json-reporter#57]
Will there be any support for Webdriverio 7? Thank you.

**Comment by tpronk** [comment]
Hey! While wdio-json-reporter gives a warning that it requires WebDriverIO v6 as a peer-dependency, as far as I can see, it works just fine with WebDriverIO v7

**Comment by razielron** [comment]
doesn't work for me on v7. will it be fixed?

**Comment by fijijavis** [comment]
@razielron What are the issues you have?  I'm not using WDIO on a regular basis any longer but don't mind helping keep the package up to date or approving PRs for things that need to be fixed.

**Comment by razielron** [comment]
@fijijavis Thank you for the quick response,
After digging in I found that I was inserting the reporter in the wrong conf key, sorry about that.
So it is working, but I also get the error: `ERROR @wdio/sync: TypeError: uuidv5 is not a function`
Probably an issue on my end.
Thanks anyway!

Edit: I've change it to uuidv4 and it works, can we have that change or fix it with v5? thanks!

**Comment by benebsiny** [comment]
So...is it now fixed? I have the same peer-dependency issue.
(Only occurred in Windows. There is no problem in Linux.)

**Comment by PetrKnedlik** [comment]
This should be probably fixed with v3.0.0

**Comment by christian-bromann** [comment]
Since this project doesn't seem to be maintained anymore, we have taken the source and added it to the WebdriverIO core project. You can now use it with WebdriverIO v8 by replacing the package from `wdio-json-reporter` to `@wdio/json-reporter`. The rest should work the same way. Let me know if you encounter any issues and feel free to raise issues around this reporter in the [main repository](https://github.com/webdriverio/webdriverio) moving forward.

**Comment by PetrKnedlik** [comment]
yees, finally. Thank you @christian-bromann 🖤
