### ISSUE TITLE
wdio vs 8 support?

### ISSUE THREAD

**Issue by pmerwin** [fijijavis/wdio-json-reporter#73]
plans to support vs 8?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: wdio-json-reporter@3.0.0
npm ERR! Found: @wdio/cli@8.1.2
npm ERR! node_modules/@wdio/cli
npm ERR!   @wdio/cli@"8.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cli@"^7.16.3" from wdio-json-reporter@3.0.0
npm ERR! node_modules/wdio-json-reporter
```

**Comment by PetrKnedlik** [comment]
Any news? Still facing the same issue as @pmerwin. --force install made it work tho

**Comment by kotlinska** [comment]
I faced the same issue. There are any plans with new version of wdio ? :)

**Comment by gforepsly** [comment]
Still present in wdio 8.4.0... Frustrating

**Comment by seeplusplus** [comment]
Opened #76 to address this. In the mean time [I have forked this package and it has worked for me](https://www.npmjs.com/package/@seeplusplus/wdio-json-reporter).

**Comment by christian-bromann** [comment]
I am happy to take this on once we get this moved into the community org, see #63

**Comment by christian-bromann** [comment]
Since this project doesn't seem to be maintained anymore, we have taken the source and added it to the WebdriverIO core project. You can now use it with WebdriverIO v8 by replacing the package from `wdio-json-reporter` to `@wdio/json-reporter`. The rest should work the same way. Let me know if you encounter any issues and feel free to raise issues around this reporter in the [main repository](https://github.com/webdriverio/webdriverio) moving forward.
